language: ruby
sudo: false

script:
  'bundle exec $CHECK'

notifications:
  email: false

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

matrix:
  include:
    - rvm: 2.3.1
      env: CHECK=rspec
    - rvm: 2.3.1
      env: CHECK=rubocop
    - rvm: 2.5.5
      env: CHECK=rspec
