language: rust
matrix:
    fast_finish: true
    include:
        # Version in appveyor
        - rust: 1.23.0
        # Version we build and ship pe-client-tools with
        - rust: 1.18.0

sudo: false

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

script:
  - cargo build --verbose
  - cargo test --verbose

notifications:
    email: false