environment:
  OPENSSL_INCLUDE_DIR: C:\OpenSSL\include
  OPENSSL_LIB_DIR: C:\OpenSSL\lib
  OPENSSL_LIBS: ssleay32:libeay32
  matrix:
  - TARGET: i686-pc-windows-gnu
    BITS: 32

install:
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-1_0_2e.exe"
  - Win%BITS%OpenSSL-1_0_2e.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.4.0-${env:TARGET}.exe" -FileName "rust-1.4.0.exe"
  - ps: .\rust-1.4.0.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - SET PATH=%PATH%;C:\rust\bin;C:\MinGW\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo build
  - cargo test