environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.4.0-${env:TARGET}.exe" -FileName "rust-1.4.0.exe"
  - ps: .\rust-1.4.0.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - cargo build --verborse
  - PATH=$PATH:./target/debug puppet-pdb --version