version: 1.3.0.{build}
environment:
  OPENSSL_LIBS: ssleay32:libeay32
  matrix:
  - TARGET: i686-pc-windows-gnu
    OPENSSL_DIR: C:\OpenSSL-Win32
  - TARGET: x86_64-pc-windows-msvc
    OPENSSL_DIR: C:\OpenSSL-Win64
install:
  - ps: wget "https://static.rust-lang.org/dist/rust-1.23.0-${env:TARGET}.exe" -OutFile "$pwd\Rust.exe"
  - Rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

# Don't run doctests due to rust-lang/cargo#1592
test_script:
  - cargo build --verbose
  - cargo test --verbose
