[package]
name = "rust-puppetdb-cli"
version = "0.1.0"
description = "PuppetDB CLI tool in rust."
readme = "README.md"
documentation = "http://ajroetker.github.io/rust-puppetdb-cli/index.html"
repository = "https://github.com/ajroetker/rust-puppetdb-cli"
license-file = "LICENSE"
keywords = ["puppet", "puppetdb", "puppetdb-cli"]
authors = ["Andrew Roetker <andrew.roetker@puppetlabs.com>"]

[lib]
name = "puppetdb"
path = "src/lib.rs"

[[bin]]
name = "puppet-db"
path = "src/db.rs"

[[bin]]
name = "puppet-query"
path = "src/query.rs"

[dependencies]
beautician = "0.1.*"
hyper = "0.7.*"
docopt = "0.6.*"
rustc-serialize = "0.3.*"
url = "0.5.*"
openssl = "0.7.*"

[dependencies.multipart]
version = "0.3.*"
default-features = false
features = ["hyper", "client"]
