[package]
name = "puppetdb"
version = "1.1.1"
description = "PuppetDB CLI tool in rust."
readme = "README.md"
documentation = "http://puppetlabs.github.io/puppetdb-cli/index.html"
repository = "https://github.com/puppetlabs/puppetdb-cli"
license-file = "LICENSE"
keywords = ["puppet", "puppetdb", "puppetdb-cli"]
authors = ["Andrew Roetker <andrew.roetker@puppet.com>", "Ryan Senior <ryan.senior@puppet.com>"]

[lib]
name = "puppetdb"
path = "src/lib.rs"

[[bin]]
name = "puppet-db"
path = "src/db.rs"

[[bin]]
name = "puppet-query"
path = "src/query.rs"

[dependencies]
#kitchensink = "0.1"
hyper = "0.8"
docopt = "0.6"
rustc-serialize = "0.3"
url = "0.5"

[dependencies.multipart]
version = "0.7"
default-features = false
features = ["hyper", "client"]

[dependencies.kitchensink]
path = "../rust/rust-kitchensink"

[features]
default = []
token-auth = []

[dev-dependencies]
tempdir = "0.3"
