on: pull_request
name: go-check
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/puppetlabs/puppetdb-cli/
    - name: Install pre-requisites
      if: matrix.platform == 'ubuntu-latest'
      run: go get -u golang.org/x/tools/cmd/goimports golang.org/x/lint/golint
    - name: Format
      if: matrix.platform == 'ubuntu-latest'
      run: cd ./src/github.com/puppetlabs/puppetdb-cli/ && make format
    - name: Vet
      if: matrix.platform == 'ubuntu-latest'
      run: cd ./src/github.com/puppetlabs/puppetdb-cli/ && make vet
    - name: Lint
      if: matrix.platform == 'ubuntu-latest'
      run: cd ./src/github.com/puppetlabs/puppetdb-cli/ && make lint
    - name: Build
      run: go build ./src/github.com/puppetlabs/puppetdb-cli/
    - name: test
      run: go test ./src/github.com/puppetlabs/puppetdb-cli/...

